version: "3"
services:
  web:
    build: .
    command: bash -c "uvicorn fastapi_energo.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - devices_db
      - anagrams_db

  devices_db:
    image: postgres
    volumes:
      - ./data/devices:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  anagrams_db:
    image: redis
